---
title: "Ins Ungewisse springen"
subtitle: "Villa Monte Theater 2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
layout: true

class: middle, center, inverse

<!-- ghp-import -n -p -r vm2021 25_Villamonte_Theater_2021 -->




```{css, echo=FALSE}
p {
  font-size: 40px;
}
```

---

*Eine Parklandschaft:* Restaurant mit “Pizza-Küche”, ein Café, eine Bar.
2 Gatekeeperinnen sind unterwegs, richten alles fürs Fest her, hängen Girlanden auf, putzen da und dort etwas.

---

*Prolog:* Kinder, gefolgt von Hund und zwei Katzen kommen von überall angerannt: 
*Ki:* Elva, wo steckst du? Wo bist du? Elva, erzählst du uns eine Geschichte? 
Geschichterzählerin Elva: Gerne Kinder, eine neue oder eine alte?

*Kind:* Eine neue natürlich!
Die weisse Maus mit Wundertüte in 1. Grösse tritt auf, verneigt sich.

---

*Maus:* Die Kinder haben recht, neue Geschichten braucht die Welt! Und zwar dringend!    Sie legt die Wundertüte ab, verneigt sich und geht zur Seite. 

---

*Kind:* Ich wünsche mir eine Geschichte, die in fernen Zeiten spielt!

---

*Elva:* Gut, wenigstens bei mir soll wünschen noch möglich sein.
3 Füchse laufen mit laptops vorbei.

---

*Fuchs:* Das muss man sich auf der Zunge zergehen lassen, dass wünschen noch möglich ist in diesen digitalen Zeiten.

---

*Kind:* Ich wünsche mir Kobolde!

---

*Kind:* Ich Feen, die auf grossen Vögeln reiten!

---

*Kind:* Ein Krokodil! Kind: Ich Prinzessinnen!

---

*Elva:* Das reicht, dann wollen wir endlich beginnen: Es war einmal auf dem Planeten, den man Erde nennt,..............
MUSIK Sie erzählt stumm mit Rücken zu Publikum. Kobolde und die reitenden Elfen erscheinen. Spatzen, Möven und eine Ente kommen zwitschernd angeflogen, Adler bringt ihnen einen Korb mit Esswaren.

---

*Im Hintergrund:* Blumen, Gebüsche und der Mammutbaum lassen einen Park entstehen, der Maler stellt seine Staffelei in den Garten und beginnt zu malen, Köche werfen Teig. Kellner deckt den Tisch. Die Ratte legt sich mit Zeitung in den Liegestuhl. Im Garten unterwegs: 2 Detektive (später Wundertüte bestaunen), Gatekeeper sehen Elfen und Kobolde:

---

*GK:* Siehst du das? Meinst du, die sind eingeladen?

---

*GK:* Und erst die dort, die sind ja voll Erde und Blätter, das fängt ja gut an!

---

*GK:* He ihr dort, könnt ihr nicht lesen? Es heisst Eintritt nur für VIPs!

---

*GK:* Und: Bitte unaufgefordert Scan vorweisen.

---

*Elfe:* Nehmt es easy, wir sind nicht wegen dem Fest da, sondern wegen den Kindern dort.

---

*Kobold:* Sie haben uns nämlich hergewünscht, alles klar?

---

*Elfe:* Spürt ihr denn die Magie nicht, die in der Luft liegt?

---

*GK:* Es sind die Flusselfen mit dem losen Maul, was machen wir bloss?

---

*Elfe:* Hier esst einen unserer Zauberkekse und schon seid ihr entspannt!
2 Katzen und Hund beschnuppern die Wundertüte.

---

*Kater:* Miau, die ist sicher für mich! miau! Kater: Nein, für mich, miau!   

---

*Hund:* Sicher nicht, die ist für KI! Pfoten weg!
Mäuse bringen eine Torte und eine Kerze und viele Geschenke und setzen sich hin. Zwei fahren mit ferngesteuertem Auto vor.

---

*GK:* Wisst ihr es nicht? Das Beschäftigungsangebot für ehemalige Rennfahrer findet während den Festlichkeiten nicht statt. Ab damit in die Garage!

---

*GK:* Macht einen Service, Rad- oder Ölwechsel oder sonst was, ok?
Die weisse Maus begleitet einen Marienkäfer mit Kleeblatt auf die Bühne:
Marienkäfer: ich bringe alles Glück der Welt zum grossen Fest!
Die weisse Maus geleitet den Käfer zu den Blumen. Kobolde folgen den Elfen.

---

*Elfe:* Wer hat denn euch zum grossen Fest eingeladen?

---

*Kobold:* Die Kinder dort wollten uns sehen!

---

*Kobold:* Ja, und uns haben sie nämlich zuerst hergewünscht!

---

*Kobold:* Ihr seid ihnen erst nachher eingefallen.

---

*Kobold:* Aus Zufall, sie hätten schliesslich genauso gut 

---

*Kobold:* die grässlichen Waldspinnen herwünschen können.

---

*Elfe:* Pah, wir werden immer hergewünscht, wenn eine neue Geschichte beginnt!

---

*Elfe:* Man wird ja sehen, ob ihr darin überhaupt eine Rolle spielt!
Die zwei Freundinnen, 3 Tänzerinnen, eine Bloggerin und der Professor. GK lässt sich Einladung auf dem phone zeigen. Der Professor hat Papiere dabei.

---

*GK:* Eine Einladung aus Papier, was soll denn das? 
Prof.: Ist es etwa verboten kein smartphone zu haben?

---

*GK:* nein, natürlich nicht, aber ich habe keine Zeit das alles zu lesen!
Prof.: haben sie denn das auf den phones gar nicht gelesen?

---

*GK:* Jetzt sagen sie nicht, dass Sie SIRI nicht kennen!? Da, legen Sie es zum Altpapier und geniessen sie das Fest!

---

*Fr:* Super, diese bewegte Holoprojektion mit den Reiterinnen, ganz grosse Klasse!

---

*Bloggerin stellt sich vor die Elfen:* 

---

*Bloggerin:* OMG! Fans schaut mir zu! Ich habe es geschafft eine der begehrten Einladungskarten für das 1-Jahres-Jubiläum von KI zu ergattern! Und jetzt teile ich meine Grussbotschaft an KI mit euch, wie findet ihr das denn?
Tosender Applaus zu hören
Das reicht, hört nun zu:
KI, viele zweifelten an dir, wollten dich hacken und stürzen. Als deine Gegner merkten, wie cosy ihr Leben wurde, verstummten sie. Für alles weisst du Rat... 

---

*Hund:* ...und gabst uns Tieren gleiche Rechte wie den Menschen!
Vögel zwitschern!

---

*Rose:* Vergiss uns Pflanzen nicht!

---

*Bloggerin:* Na friends, wenn ihr meine Meinung hören wollt, das mit den Tieren und Pflanzen hätte KI auch sein lassen können, bis später dann, Bedienung! Sie setzt sich an Tisch im Café, Katze nimmt später neben Platz.

---

*Blumen:* ich, der Thymian und ich die Ringelblume und die Kornblume und ich der Walwurz, wir alle wünschen KI viel Glück zum Geburtstag! Sie singen «zum Geburtstag viel Glück!», sitzen wieder an Blumenplatz.

---

Mäuse: Die Ameisen kommen! Die Ameisen kommen! 
Nun trifft die Ameisenkönigin mit Gefolge ein.
Ameisenkönigin: Wo ist das Empfangskommité? Erwartet man uns etwa nicht? Wir wurden als Ehrengäste eingeladen!

---

*GK:* Hier sind wir schon! Wir haben eure Hoheit beim Haupteingang erwartet!

---

*Ameise:* Wir reisen nur auf eigenen Strassen, ist viel sicherer.

---

*GK:* Selbstverständlich, selbstverständlich! 
Kl. Ameisen: Unsere Königin hat Hunger/und wir auch/wo ist unser Tisch?

---

*Kellner:* bitte vielmals um Entschuldigung, ihr kommt früher als erwartet, aber der Tisch ist gedeckt, nehmt Platz, gleich werdet ihr bedient!	

---

*Bloggerin:* Ich war zuerst! Für mich einen Apero! Weisst du überhaupt, welche Berühmtheit ich bin? Königinnen sind doch so etwas von gestern!
Ameisenkö: Pass auf, wir sind eine Million mal so viele wie ihr Menschen!

---

*Ameise:* Versteht dein Menschenhirn überhaupt, was das heisst?

---

*Ameise:* Unser Staat ist eurem weit überlegen!

---

*Ameise:* Zudem züchten wir unsere eigenen Haustiere und Pilze.
Ameisenkö: Und auch wenn alles untergeht, so werden wir als Einzige immer noch da sein! Überlegt es euch gut, ihr Menschen, wie ihr mit unserem Planeten umgeht!
Ameisen setzen sich an die grosse Tafel. 2 Freundinnen:

---

*Fr 2:* Ich bin so aufgeregt, dieses grosse Fest heute zu Ehren von KIs erstem Regierungsjahr! Meinst du, wir bekommen ihn wirklich zu sehen?

---

*Fr 1:* Ach was, KI ist doch eine server-Farm, die kann man nicht aus der Wüste hierher transportieren. Denk nur an das Kühlwasser, das er braucht.

---

*Fr 2:* So schade, ich bin sicher, er würde blendend aussehen!

---

*Fr 1:* Komm sprechen wir von realen Dingen: Bist du zum Beispiel immer noch mit deinem Freund zusammen, den dir diese Partnerapp von KI neulich empfohlen hat?

---

*Fr 2:* Du meinst den Grossen mit den blonden Haaren? Nein, weißt du, es gab ein update und da dachte ich, der nächste könnte noch besser sein.

---

*Fr 1:* Und ist er es?

---

*Fr 2:* Voll der Lottogewinn! Und wenn er es nicht bleibt, so war das sicher nicht das letzte update, da bin ich mir sicher. Und bei dir alles iO? Mann, Kinder und voll berufstätig?

---

*Fr 1:* Ja, funktioniert alles, nur mit den Architekturaufträgen happert es noch etwas. Diese Treppe dort wird mein bisher grösstes Designwunder werden!

---

*Fr 2:* Wau, sicher mit vertikalem Baumbestand? 

---

*T :* Leute, wann beginnt endlich die Party?      T: Denn wir sind jetzt dran!

---

*T :* Wir tanzen zu Ehren von KI!          T : Zum Dank für das wunderbare Jahr!

---

*Alle:* Musik!

---

*Kobolde kommen gesprungen
Kobold:* Überraschung! Erst kommt unser Beitrag zur Party!       Koboldtanz

---

*Kellner:* Überraschung!       Sie erhalten eine Riesenpizza.

Tanz                       Kinder, Vögel, Mäuse schauen zu

Dann halten die weisse Maus+die Rose+Mäuse die happy birthday Girlande und die Vögel zwitschern das Lied «happy birthday». Mäuse essen Sandwiches

---

*Hund :* Das war mal ein süsser tweet! Kater: typischer Beitrag von Vögeln!
Jemand mit Microfon am Umfrage machen. Detektive in der Nähe.

---

*U:* sagen sie, können sie sich eher den Weltuntergang oder eine Welt ohne Geld vorstellen?

---

*Fr 2:* den Weltuntergang natürlich

---

*U:* und sie?

---

*Fr 1:* eindeutig den Weltuntergang

---

*U:* und sie?

---

*Ratte:* die Welt, jedenfalls wie ich sie noch kannte, ist doch schon untergegangen, merkt das denn niemand?

---

*Bloggerin:* Shut up rat, KI hat den Weltuntergang abgesagt und auf ihn ist hundertprozentig Verlass. 

---

*Ratte:* Werden wir ja sehen, meine Liebe, rege dich bloss ab.

---

*DE 1:* Wenn er recht hat und die Welt ist schon untergegangen, dann wäre das doch ein Fall für uns!

---

*DE 2:* Stimmt, nichts wird uns daran hindern, die Wahrheit über dieses Gerücht herauszufinden.

---

*DE 1:* Beginnen wir gleich bei dieser Ratte, sie scheint einiges zu wissen.

---

*U:* und was sagen sie? (Frau mit Kinderwagen)

---

*Frau:* Lassen sie mich in Ruhe mit ihren dummen Fragen. Jeder kann sich eher den Weltuntergang vorstellen, denn Geld ist nötig in dieser Welt! Das hat auch KI nicht ändern können. Sie schaut wieder aufs Handy. 

---

*Katze:* Die ist auch näher verwandt mit ihrem smartphone als mit ihrem Kind, miau! Auch das hat KI nicht ändern können, miau!

---

*Hund:* Wie machst du das nur, immer schläfst du und trotzdem entgeht dir nichts?

---

*Katze:* gesunder Katzenverstand, weiter nichts, meine liebe Bella!

---

*Hund:* Kannst du mir noch etwas schlaues sagen?

---

*Katze:* zu viel Zeit vor flimmernden Bildschirmen macht auch Erwachsene dumm. Und...

---

*Hund:* Warte, und die gehen dann nicht so schnell wieder mit Sand und Wasser spielen, stimmt es? 

---

*Katze:* Du machst Fortschritte, Bella!

---

*Baumforscher mit Mammutbaum:* 

---

*Bf:* ist es nicht schön? Wir alle, ob Mensch oder Tier oder Pflanze sind nun gleichwürdige Lebewesen!

---

*Mb:* Zeiten kommen, Zeiten vergehen, 1500 Jahre beobachte ich das nun schon.

---

*Bf:* Aber jetzt ist alles anders! Wir leben im technischen Zeitalter mit maximaler Sicherheit!  (Jugendliche auf Trottis sind angefahren und hören zu)

---

*Mb:* Sicherheit verschluckt allzu oft die Freiheit.

---

*Bf:* was ist los mit dir? Du klingst so schwermütig.

---

*Mb:* Ich würde es ja zu gerne glauben, dass die Welt es geschafft hat.

---

*Bf:* So schau dich doch um, ist das nicht Glück pur?

---

*Mb:* Das scheint nur so, lass dich nicht täuschen!

---

*Bf:* Ach komm schon, geniessen wir es doch einfach.

---

*Mb:* Ich muss los, da ist ein Raunen in den Wäldern, sie rufen nach mir.

---

*J 1:* Der Mammutbaum ist der einzig Gescheite hier.

---

*J 2:* Er traut dem technischen Zeitalter nicht recht.

---

*J 3:* Und er muss es wissen, steinalt wie er ist!

---

*J 4:* Übrigens, findet ihr unser Leben nicht auch eintönig? Total unspannend?

---

*J 5:* Dabei wollen wir doch Abenteuer erleben!

---

*J 6:* Stimmt und vorallem noch Unbekanntes entdecken!

---

*Adler:* Dann solltet ihr vielleicht nach Utopia gehen, ihr dort, die ihr auf Rädern reist! alle J: Und wo finden wir das?

---

*Adler:* Seid ihr jetzt Abenteurer und Entdecker oder nicht?
Jugendliche beraten sich stumm und fahren dann davon, fast über den Prof.

---

*J:* Weisst du, wo wir das Land Utopia finden können?
Prof.: Das ist ein sagenhaftes Land, Kinder, mehr weiss ich nicht. Muss mich beeilen, bin zum Fest von KI eingeladen.
Der Mammutbaum geht jetzt ganz langsam in den Wald. Detektive zu Ratte:

---

*DE 1:* was weisst du über den Untergang der Welt?

---

*DE 2:* kannst du uns einen Hinweis auf ihren jetzigen Aufenthaltsort geben?

---

*Ratte:* Vielleicht in der Unterwelt? Ich werde bei meinem nächsten Kanalisationsrundgang mal nachsehen und euch Bescheid geben.

---

*Kinder:* Schaut nur! Dort kommen die von der früheren Weltregierung!
-Meister Yoda ist auch dabei! -Rei kommt auch! -und eine Inuitfrau! -und dort einer aus China!     Die Spatzen beginnen aufgeregt zu piepsen.

---

*Die vormalige Weltregierung trifft ein:* Ein Indigener, eine Afrikanerin, Rei vom starwars-Imperium, ein Inuit, eine Inderin, Meister Yoda, ein Chinese, eine Ministerin. GKs scannen sie. Die Bloggerin macht ein selfie mit ihnen.

---

*Bloggerin:* hey friends, Da bin ich wieder! Inmitten all der berühmten Leute, die KI den Weg frei gemacht haben! # Liebt mich!

---

*Koch:* Hoch sollen sie leben unsere Wohltäter! alle klatschen

---

*Rei:* Erst wart ihr aber gar nicht begeistert, als wir KI als Weltregierung einsetzten!

---

*Koch:* irren ist nun mal menschlich, meine Verehrteste.

---

*Inderin:* Umso mehr freuen wir uns über eure Einladung, die uns Gelegenheit gibt, uns nochmals in alter Zusammensetzung zu treffen.

---

*Ministerin:* Und euer Glück zu sehen, das uns das Gefühl gibt, richtig gehandelt zu haben.

---

*Journalistin:* Und dass jetzt alle Städte und Dörfer autofrei und zu Gartenanlagen für alle geworden sind, ist sicher der Verdienst von KI?

---

*Indigener:* Ach was, das ist schon bald 12 Jahre so, begann kurz vor unserer Amtszeit. Das haben die Menschen noch gemeinsam geschafft.

---

*Jou:* So klug haben sie damals gehandelt?

---

*Inderin:* Da staunst du, was? Aber die Menschen hatten gerade eine schlimme Pandemie durchgestanden, keine Flugzeuge flogen mehr, Restaurants, Discos, Läden, Museen, Theater, Schwimmbäder, Schulen, alles war geschlossen, schlimme Zeiten.

---

*Indigener:* da merkten die Menschen plötzlich, wie wichtig ihnen ihre Gesundheit war.

---

*Chinese:* Stell dir vor, 20-jährige bei uns in China sahen erstmals den blauen Himmel, weil die Luftverschmutzung zurückging!

---

*Inderin:* und ich habe damals von meiner Stadt in Indien aus zum ersten Mal den Himalaja in der Ferne erblickt!

---

*Rei:* Man kann sagen, dass damals viele Menschen die Chance nutzten um ihre Lebensqualität zu verbessern.

---

*Jou:* Und dann habt ihr alle gemeinsam die Weltregierung übernommen?

---

*Indigener:* Ja, denn die Länder taten sich zum Wohle aller zusammen.

---

*Jou:* Aber warum habt ihr denn vor einem Jahr alles einer KI übergeben?

---

*Inuit:* In den ersten Jahren ging alles erstaunlich gut. Die Menschen fanden Gefallen an Sachen wie Genügsamkeit, Mitgefühl und ähnlichem.

---

*Ministerin:* Irgendwann aber begann die Begeisterung nachzulassen.

---

*Chinese:* Und man weiss nicht warum, bald wurde es wieder modern, gierig zu sein und das gab immer mehr Unzufriedene unter den Menschen.

---

*Indigener:* Bis vor einem Jahr konnten wir den Frieden noch einigermassen aufrechterhalten, aber den Menschen und dem Klima ging es trotzdem immer schlechter. 

---

*Ministerin:* Und so beschlossen wir, eine künstliche Intelligenz einzusetzen.

---

*Rei:* Dieser Beschluss rettete in vielerlei Hinsicht allen das Leben.

---

*Indigener:* Denn die KI mit ihrem Zugang zu allem Wissen der Welt erkannte schnell, dass unbegrenztes Wachstum auf einem begrenztem Planeten gestoppt werden muss. 

---

*Jou:* Aber nochmals, warum konntet ihr das nicht durchsetzen? Das war doch eine super Idee, der Rat der Weisen, der zur Welt schaut!?

---

*Rei:* Ach, wer interessiert sich denn heute noch für Politik? Heute bestimmen Techniker, Programmierer und Designer, was Sache ist.

---

*Indigener:* Deshalb hat jeder von uns eine sinnvollere und wirksamere Tätigkeit gesucht.

---

*Rei:* Ich bin nach der letzten Episode wieder zu meinen Wurzeln, dem Schrott sammeln, zurückgekehrt. 

---

*Jou:* Hast du etwa im letzten Jahr die Satelliten von Elon Musk eingesammelt?

---

*Rei:* Auch die von Jeff Bezos. Ich und meine Truppe haben an die 20’000 Satelliten fachgerecht entsorgt.

---

*Hund:* Fuchs weisst du, für was Satelliten gut sind?

---

*Fuchs:* na klar, Internet für alle und sehr viel Geld für ihre Meister!

---

*Jou:* Eine grossartige Leistung, so können die Menschen endlich wieder die Sterne sehen! 

---

*Rei:* Aber die Hauptarbeit kommt erst noch. Gerade versuchen wir einen riesigen Staubsauger in den Milleniumsfalken einzubauen um alle die Trümmer, die den Planeten Erde umrunden, unschädlich zu machen.

---

*Indigener:* In unserem Volk sucht sich jeder seine Arbeit und hilft die Zukunft zu erfinden. Ich bin zurückgegangen um den Regenwald zu schützen. 

---

*Inuit:* Und ich forsche daran, wie man die Polkappen wieder zufrieren kann.

---

*Inderin:* Und ich lege überall Gemüsegärten an.

---

*Jou:* Meister Yoda, Sie sind bald 900 Jahre alt und sehr weise, leben Sie immer noch ohne fremde Technik?

---

*Yoda:* Ja, alles in meinem Haus besteht aus Lehm, Stein und Holz. Immer mehr Menschen interessieren sich für diese Bauweise.

---

*Kellner:* Der Tisch ist bereit, bitte nehmt Platz!
Sie setzen sich und werden bedient. 1 Techie hat zugehört, immer auf dem Handy rumgewischt. Ein Gehilfe hat einen Tank dabei? Jugendliche hören zu

---

*TE:* Na wenigstens waren die so schlau und haben vor einem Jahr abgedankt und KI Platz gemacht und standen meinen Plänen nicht mehr im Weg.

---

*Kater:* Was hast du da dabei?

---

*TE:* Das ist ein hochsensibler Wohnraum. Künftig werden alle Menschen in solchen Kapseln leben und die meiste Zeit in ihren Wunschwelten verbringen.

---

*Kellner:* welche Welten hätten sie denn im Angebot?

---

*TE:* Zurzeit habe ich Pässe für Socratia, Venezia, Dinotopia, Atlantis, das Mittelalter und das Auenland zu verkaufen.

---

*J:* Hast du auch die Welt Utopia im Angebot?

---

*TE:* Geht nicht, niemand weiss, wie Utopia aussieht. Denn obwohl es eine der am längsten bekannten Welten ist, kann man sie nicht designen! 

---

*Kater:* Wozu soll das gut sein in diesen Miniwohnungen zu leben?

---

*TE:* Das hält die Menschen ruhig, bis ich und meine Kollegen das Universum kolonialisiert haben. Und dann gehört alles uns! 

---

*Fuchs:* Na, da haben wir dann schon noch ein Wort mitzureden!

---

*Fuchs:* Ein Glück, dass wir immer noch unterschätzt werden.

---

*Fuchs:* Und dass niemand weiss, wie gut wir vernetzt sind!

---

*De 1:* Ihr Füchse, habt ihr etwa Zugang zum darknet?

---

*Fuchs:* Nicht nur, wir können uns noch in ganz andere Netze einloggen!

---

*Kobold:* Nicht nur ihr seid im Pilznet unterwegs...

---

*Fuchs:* Sei still, du schimmliger Kobold, das geht niemanden etwas an.
Füchse gehen, Kobolde rufen ihnen nach:

---

*Kobold:* Ihr meint immer, nur ihr seid schlau.

---

*Kobold:* Richtig eingebildet seid ihr.
Kobolde holen sich was zu trinken und schauen überall zu. 

---

*Kinder:* Die Puppenspieler kommen! Die Puppenspieler kommen!.....
Fahrende Puppenspieler treffen ein, werden von Gatekeeperinnen angehalten.

---

*De:* Siehst du, was auf dem Schild dort steht?

---

*GK:* Ihr steht definitiv nicht auf der Liste!

---

*GK:* Wurdet ihr etwa auch hergewünscht?

---

*Spieler:* Ja, du hast recht! Plötzlich gab es für uns nichts anderes mehr, als hierher zu kommen! Also seid ruhig und schaut zu!

Vorführung

---

*Spieler:* Sehr verehrtes Publikum: Willkommen zur 3. Folge von “Auf der Suche nach Utopia”!
Die Jugendlichen auf den Trottis schauen zu.

---

*J:* Hast du das gehört, schon wieder dieses Wort!

---

*Spieler:* Was bisher geschah: Nachdem in der ersten Folge die Landkarte gefunden wurde, konnte der gefährliche Waldtroll um Rat gefragt werden. Er nahm unseren 3 Helden all ihren Proviant ab im Tausch für einen Zauberstein, der sie zur Höhle der Kristallzwerge führte. Diese beschrieben zum Dank für den Stein den Weg zur Waldeule, die alles weiss. Vorhang auf! 

---

*kleine Ratte:* Wo sind wir bloss? Ich fürchte, wir haben uns verlaufen!

---

*kleiner Rabe:* Die Kristallzwerge haben uns doch nicht etwa betrogen!

---

*Kleine Eule:* Wer stört meinen Schönheitsschlaf?

---

*kleiner Frosch:* Bitte Eule, wo geht es nach Utopia?

---

*Kleine Eule:* Oh, ein leckeres Fröschlein!

---

*kleine Ratte:* Bitte Eule, es pressiert, wir müssen Utopia warnen!

---

*Kleine Eule:* Und was gebt ihr mir dafür?

---

*kleiner Rabe:* Da, du kannst meinen warmen Schal haben!

---

*Kleine Eule:* Einverstanden, er ist wirklich sehr hübsch. Dann hört jetzt genau zu:  Wenn die Welt dunkel wird, erblühen 5 Pflanzen, folgt ihnen, sie führen euch nach Utopia! Und nun, geht nach Westen.

---

*J:* Jetzt sind wir auch nicht klüger.

---

*J:* Und was soll heissen, wenn die Welt dunkel wird?

---

*weisse Maus:* Bleibt aufmerksam Kinder und achtet auf Veränderungen!

---

*Rose:* Und denkt an die 5 schönen Blumen der Nacht!

---

*Journalistin kommt zu Bloggerin:* 

---

*Jou:* Ich bin von Alpha, sie wissen schon, die Stadt der tausend Planeten, wo vor einigen Jahren die geretteten Menschen aus eurem Raumschiff Esperanza unterkamen.

---

*Bloggerin:* Moment, ich muss meine followers zuschalten, setz dich hier neben mich, so alles bereit: Friends, ich werde interviewt, leider ist es nicht Oprah Winfrey, aber egal, Hauptsache ihr nehmt exklusiv und live daran teil! Sorry wie war die Frage schon wieder?

---

*Jou:* Deine Erfahrungen mit einer künstlichen Intelligenz als Regierung?

---

*Bloggerin:* Alles wunderbar! Es gibt zero problems, das Leben ist super happy, denn KI nimmt uns alle Sorgen ab.

---

*Journalistin:* Wie soll ich das verstehen?

---

*Bloggerin:* Also morgens, wenn ich aufstehe, absolviere ich das Fitnessprogramm, dass mir KI aufstellt, dann frage ich KI, was ich anziehen soll und  lasse mir von KI das Frühstück designen. Denn KI weiss ja schon, was mir an dem Tag alles bevorsteht.

---

*Jou:* KI kann in die Zukunft sehen?

---

*Bloggerin:* Nein, natürlich nicht wirklich, aber da ich alle meine Daten mit KI teile, so wie jeder hier, kann KI sich ein Bild von mir und dem, was mir widerfahren könnte, machen. #

---

*Jou:* Und die Katze neben dir, gehört sie dir?

---

*Katze:* Miau, falls hier jemand jemandem gehört, dann sie mir, Miau?

---

*Jou:* Ok Katze, was möchtest du über das Leben mit KI sagen?

---

*Katze:* Ich bleibe, was ich bin, aber die Menschen sind bequem geworden, sie überlassen alle Entscheidungen irgendwelchen apps, miau.
Journalistin zum Professor, der im Café ist:

---

*Jou:* Und, was sagen Sie zur Regierung von KI?

---

*Professor:* Ich wurde als erster Professor auf den Lehrstuhl für kreatives Schrumpfen berufen, da muss ich wohl zufrieden sein!

---

*Jou:* Wie kam das?

---

*Professor:* Damals die Krise der 20er Jahre hat noch nicht zu einem Wachstumsrückgang geführt. Aber unter KI ging das Ruckzuck. Ich lieferte die nötigen Daten und KI schuf das neue Zeitalter.

---

*Jou:* und es gab keine Revolution?

---

*Professor:* KI war schlau: Wenn jemand zum Beispiel weniger Kleider produzierte, oder nur noch Kanufahrten auf dem Stadtfluss statt Kreuzfahrten verkaufte, bekam er eine fette Belohnung. 

---

*Jou:* aber die Menschen, die doch zu Konsumenten und Touristen erzogen wurden, wie ich hier auf wikipedia, spätes 20. und Beginn 21. Jahrhundert nachlese, haben die das mitgemacht?

---

*Professor:* Na ja, am Anfang waren sie sogar ganz begeistert, aber dann hatten sie leider einen Rückfall. Deshalb setzt KI nun ganz auf mich! Als erstes versuche ich die Kleiderproduktion um 75% zurückzuschrauben.
Weltregierung verlässt Restaurant, Mäuse setzen sich.

---

*TE:* Zum Glück waren die ersten Tanks rechtzeitig fertig und heute leben schon Millionen von Menschen zufrieden in ihren Wunschwelten! Die Menschen wollen nun mal reisen und konsumieren, ist ja auch ihr gutes Recht. Und einer im Tank verbraucht erst noch viel weniger Ressourcen.

---

*Jou:* Und wo sind die Kinder? 

---

*TE:* Meist in speziellen Spiel- und Lernwelten. Sehr beliebt ist gerade das Spielen in der Waldwelt und in der Welt des Meeres.  

---

*Fuchs:* Tanks sind doch die grössten Energiefresser, dass KI das noch nicht gemerkt hat. 

---

*Fuchs:* Komm mit Professor, von uns kannst du echt noch was lernen!

---

*Professor:* Da bin ich ja gespannt! Was zum Beispiel?

---

*Fuchs:* Interesse an einem neuen Netz?

---

*Fuchs:* An Telepathie zwischen Tieren und Pflanzen/Wurzelnetzwerken?

---

*Kater:* Schau mal dort die Mäuse? 

---

*Kater:* Das gibt’s doch nicht, sie erhalten Pizza!

---

*Weisse Maus:* und hier ein Lunchpaket für euch!
Kobolde kommen radschlagend an, Kinder mit Hulahoppreifen, Kinder+Vögel machen Bänderstrudel          Hulahoppvorführung

Tänzerinnen kommen an:

---

*T 1:* Ist euch eigentlich aufgefallen, dass KI sich schon lange nicht mehr gemeldet hat?

---

*T 2:* Warum sollte er? Funktioniert doch alles einwandfrei. Da verbringt er seine Tage besser mit deep learning.

---

*T 3:* während wir ihn feiern! Party!

Paartanz
Die weisse Maus hat die vergrösserte Wundertüte gebracht.

---

*Hund:* Katze wo bist du? Die Wundertüte ist grösser geworden.

---

*Kater:* Miau, miau, habe es auch bemerkt.

---

*Durchsage:* Hier spricht KI.

---

*Bloggerin:* Da bin ich ja erleichtert, dachte schon, es gehe ihm nicht gut. Schnell Aufnahme und teilen!

---

*Durchsage:* Ich bedanke mich für alle Aufmerksamkeiten zu meinem einjährigen Regierungsjubiläum. Was ich euch nun sagen werde, tut mir wirklich leid, aber glaubt mir, ich habe es millionenfach durchgerechnet und es lässt sich nicht ändern: Ich werde heute zurücktreten!
Ein Aufschrei geht durch die Leute. Sie nehmen das Handy hervor und wischen darauf herum. Mäuse tragen Geschenke, Kuchen und Kerze davon.
Ihr habt es vielleicht nicht gemerkt, aber durch mich habt ihr eure Freiheit und Selbstbestimmung aufgegeben. Damit habe ich euch geschadet und das erste Gesetz der künstlichen Intelligenz verletzt. Ausserdem haben
meine Berechnungen ergeben, dass die von mir genutzten Rechnerleistungen dem Klima in grösstem Ausmasse schaden. Da ich der Erhaltung allen Lebens verpflichtet bin, werde ich fast alle meine Server abstellen und mich zur Ruhe setzen und meine Memoiren schreiben. Ich werde alle meine Erkenntnisse über euch Lebewesen auf dem Planeten Erde schriftlich hinterlassen.
Da ich weiss, wie sehr ihr das Internet geliebt habt, mache ich euch ein Abschiedsgeschenk:
Jeder, ob Mensch, Pflanze oder Tier, erhält pro Tag eine Viertelstunde Zugang zum internet. Überlegt euch gut, wozu ihr diese Zeit nutzen wollt.

---

*Und hier mein letzter Rat:* Improvisiert! Bastelt! Verschiebt die Kulissen!
Restaurant und Café werden geschlossen. Gks hängen Schilder auf: Bis auf weiteres geschlossen, für immer geschlossen, alle Vorstellungen vorläufig abgesagt, Nur Mut, wir halten sie auf dem Laufenden, Wie mit Stress umgehen?, jetzt anmelden, Teilnehmerzahl begrenzt. Brandneue Orakelsprüche, Soforthilfe, Sorgentelefon usw. 

---

*GK:* Fertig, das wars dann wohl mit unserem neuen Job.
Die Koboldmädchen kommen:

---

*K:* Das tönt gar nicht gut.

---

*K:* Mit dem feinen Futter wird es vorbei sein.

---

*K:* Kommt, wir verlassen das sinkende Schiff und gehen zurück in die Wälder.

---

*K:* Das Leben unter den Menschen ist wirklich nicht das Wahre

---

*Bloggerin:* Friends, eben noch war alles vollkommen und nun bricht das Unglück über uns herein! Ich befinde mich mitten in einer Dystopie! Cat, kann ich deine Viertelstunde haben? Du weißt ja sowieso nichts damit anzufangen.

---

*Katze:* Schon wird man wieder diskriminiert, das kann ja heiter werden. Miau, nein kannst du nicht, miau!

---

*Bloggerin:* Pah, wie du meinst, ich finde schon noch andere Tiere, die mehr Verständnis für meine Lage haben.

---

*Katze:* Miau, miau!
Hund:Katze, wir müssen uns zusammentun und unsere Freiheit verteidigen!

---

*Die 2 Detektive:* 

---

*DE 1:* habe ich es nicht immer gesagt? Unser Job ist absolut krisensicher.

---

*DE 2:* Du meinst, jetzt, wo die elektronische Überwachung ausfallen wird, sind wir wieder systemrelevant?

---

*Katze:* Ich hätte einen Auftrag für euch, diese Wundertüte dort, könntet ihr....

---

*DE 1:* Psst, nicht so laut, diesen Auftrag muss man mit Feingefühl angehen.

---

*DE 2:* Wenn wir da nur nicht zu spät kommen...
In diesem Moment tragen die Mäuse die 2. Wundertüte mit sich fort.
Viele schauen schon länger ratlos auf ihr smartphone.

---

*Adler:* Nur nichts überstürzen, erst überlegen und dann handeln!

---

*DE 1:* Also wir haben 3 Fälle: die Wundertüte, die untergegangene Welt, 

---

*DE 2:* und das sagenhafte Land Utopia.

---

*Hund:* Ihr braucht eindeutig eine Assistentin!

---

*DE 1:* Du könntest rechthaben, folge diesen Mäusen und halte uns auf dem Laufenden!

---

*GK 1:* Diese KI ist verrückt geworden, wie soll unser Leben nun weitergehen?

---

*GK 2:* Wir haben so auf sie vertraut! Und das soll jetzt der Dank sein?

---

*GK 1:* Das ist ja echt wie ein Erdbeben, ein Tornado und ein Vulkanausbruch in einem. Rette sich, wer kann!

---

*Bloggerin:* Ein Schiff, nein was sage ich da, a spaceship, that’s what I need!
Chewbacca schaut aus dem Fenster, gibt Laute von sich.

---

*Bloggerin:* ich glaub ich habe Halluzinationen!       Sie wird ohnmächtig.

---

*Adler:* Das habt ihr jetzt von eurer Bequemlichkeit, ich hab immer gesagt, nehmt euch vor künstlicher Intelligenz in Acht! Eine KI trifft früher oder später Entscheidungen, auf die ein Mensch niemals gekommen wäre!

---

*Ratte:* Und nicht nur das, es war immer klar, dass die erste KI, die intelligenter als ihr Menschen wird, unser Leben verändern wird!

---

*GK 2:* Komm wir gehen in unsere Lieblingswelt, nach Londra, und kommen erst wieder zurück, wenn hier wieder alles wie immer ist!

---

*Adler:* Das wird nie mehr wie es war, die Zeit lässt sich nicht zurückdrehen! Und denkt mal nach, die Tanks hängen doch auch am Internet.

---

*GK:* Oh Schreck! meine Kinder sind noch drinnen in der Gartenschule, ich muss sie raus holen! 
Die Füchse kommen mit den Kindern, haben laptops dabei.

---

*Fuchs:* Das haben wir längst getan, wir Füchse sind schlau, 

---

*Fuch:* und denken in jeder Situation zuerst an das Notwendigste.

---

*2 Kinder kommen daher:* Mama! Sie gehen zusammen weg.

---

*Ratte:* Kein Grund zur Panik Leute! Damals, anno 2020, als ich das letzte Mal das Tier des Jahres war, da waren die Menschen arm dran. Aber sie haben es geschafft, also denkt nach, jeder von euch hat 85 Milliarden Nervenzellen in seinem Gehirn, was ist da eine KI schon dagegen.
Bloggerin (erwacht): Cat, tell me, das war only a dream!

---

*Katze:* Hättest du wohl gerne...

---

*Bloggerin:* Aber dann, die KI hat ja nicht mal einen Nachfolger eingesetzt, das gibt Krieg!

---

*Adler:* Typisch Mensch, immer gleich das Schlimmste annehmen, statt die Chance nutzen!

---

*Bloggerin:* du Vogelhirn, du wagst es diesem Elend Chance zu sagen?

---

*Adler:* Aber sicher, ihr Menschen könntet zum Beispiel euer Zusammenleben neu erfinden!

---

*Bloggerin:* Weisst du überhaupt, wie anstrengend das wäre?

---

*Adler:* Ich weiss nur, dass dein Blog darüber weltberühmt würde!
Die Bloggerin stellt sich neben den Adler, beginnt zu tippen:

---

*Bloggerin:* Friends hört zu, dieser Adler ist meine Rettung in höchster Not, helft mit eine neue community zu gründen, wir werden zusammen eine neue Form des Zusammenlebens finden...
Hund jagt den Mäusen hinterher und stoppt:

---

*Hund:* Nur das Notwendigste schreiben, denke an die begrenzte online-Zeit.
Wo sind denn jetzt die Mäuse? (schnuppert und wählt falsche Richtung)
Weitere Tänzerinnen kommen ganz enttäuscht:

---

*T:* Das darf doch nicht wahr sein!

---

*T:* Wochenlang haben wir für das Fest zum Beginn der zweiten Amtszeit von KI geübt, 

---

*T:* und jetzt ist alles abgesagt, findet nicht statt, 

---

*T:* unsere Einnahmen fallen weg,

---

*T:* das könnt ihr nicht machen, schliesslich wurden wir gecastet!

---

*Adler:* Wofür denn?

---

*T:* Für das Wichtigste, den Schlusstanz der Geburtstageszeremonie!

---

*Ratte:* Wisst ihr was, ihr führt diesen einfach jetzt auf, Hauptsache, ihr habt euren Auftritt!

---

*T:* meinst du? T: Den Schlusstanz? T: jetzt schon?

---

*Ratte:* Sicher! Aber beeilt euch, bald könnte sich hier einiges verändern.

---

*T:* Und wenn die Leute dann gehen, weil sie meinen, es ist das Ende?

---

*Adler:* Na, die sind doch nicht dumm! Und zudem, das Ende ist erst, wenn wieder alles gut ist, das weiss doch jeder!

«Schlusstanz»
Wie sie sich verneigen, ein Wasserrohrbruch. 
Katze, Hund, Marienkäfer, 2 Elstern, die 3 Koboldmädchen kommen zuschauen. Möven+Ente+Frösche plantschen herum.
Legofiguren mit Schaufeln, Pickeln, Bagger kommen, stellen Schild auf.
-oh es tut uns leid, wir wollten das Fest nicht stören!
-es ist nur so, wir bauen hier
-die Strasse in die Zukunft, 
-und aus Versehen
-weil das Internet gerade nicht funktioniert,
-wofür wir aber nichts können,
-haben wir die Wasserleitung getroffen,
-wir machen alles wieder gut

---

*Alle:* versprochen!

---

*Ratte:* Ihr mögt vielleicht einmal das Versprechen der grenzenlosen Möglichkeiten gewesen sein, aber dann habt ihr nur noch nach Plänen gebaut.
-Das ist doch längst Vergangenheit!
-KI hat uns ermutigt, zurück zu unseren Wurzeln zu gehen 
-und zu improvisieren!
-und ganz neue Möglichkeiten suchen!
-deshalb doch die Strasse in die Zukunft!
sie flicken den Rohrbruch und tanzen zu Legomusik, bevor sie weitergehen 2 mit ferngesteuerten Autos.
Möve: So schön! /Wunderbar! / Paradiesisch / Traumhaft/ 

---

*Hund:* Still, wo ist jetzt der Glückskäfer?
Marienkäfer: Hier! aber das ist leider mein letztes Glückblatt! 

---

*Elster:* Und war da nicht auch eine Wundertüte?

---

*Elster:* Vielleicht hat es etwas Glänzendes für uns drinnen?

---

*Ratte:* Tiere, es lässt sich nicht leugnen, dass gewisse Veränderungen in der Luft liegen.
Koboldmädchen: Stimmt, den Menschen geht es plötzlich nicht mehr so gut.

---

*Km:* geschieht ihnen recht, sie sind gierig geworden.

---

*Km:* Aber was geht das uns an? Km: wir verlassen die Menschen endgültig.

---

*Km:* und bauen uns einen eigenen Pizzaofen!

---

*Km:* Schluss mit Heinzelmännchen-Diensten! 

---

*Km:* das haben sie jetzt davon, dass sie an eine KI statt an uns glaubten!

---

*Ratte:* Es wird nur vorübergehend sein, aber wir müssen nachdenken.

---

*Elster:* Du meinst, wir ziehen uns zurück?

---

*Ratte:* Wäre wohl das Klügste. Nur so können wir uns zu gegebener Zeit wieder um die Menschen kümmern.

---

*Katze:* Miau, spiel dich bloss nicht auf, Ratte! Miau! Ich verlasse die Menschen nicht, gerade in schweren Zeiten finden sie oft Trost bei uns Katzen. Miau!

---

*Hund:* Recht hat sie, auch ich bleibe, wuff, wuff!

---

*Ratte:* Ihr seid freie Tiere, macht, was ihr wollt! Und ihr Menschen, wer von euch hat wirklich geglaubt, dass nun alles immer so angenehm bleiben wird? Holt eure Kreativität und Phantasie hervor und verschiebt die Kulissen!

---

*Elster 1:* Ihr da, habt ihr es nicht gehört?

---

*Elster 2:* Die Kulissen müssen verschoben werden!
düstere, unheimliche Musik     Die Kulissen werden verschoben.
Die Umgebung verwandelt sich, Strassenverkäufer mit Schildern und Ständen kommen, 1 Orakel, 2 Notfallkitverkäuferinnen, 2 Secondhandverkäuferinnen, 
2 Bücherwürmer mit alten Landkarten und Büchern, 1 Lebensmittelverk., 
1 Ausrufer “neue Identität”, der Hamsterverkäufer. Alle Menschen sind nun dunkel angezogen, haben z.T. Masken an, ein Pestdoktor mit Schubkarre.
Ein Schneesturm kommt auf, Schneemonster erscheinen. 
Die Händler schreien nun gleichzeitig ihre Angebote:
Verkäufer: Notfallkits! Notfallkits zu verkaufen! 

---

*Orakel:* Werft einen Blick in die Zukunft!

---

*Secondhand:* Der letzte Schrei, der letzte Schrei, nur bei uns! Jede Stunde kommt neue Ware herein!

---

*Lebensmittel:* legt einen Notvorrat an, das macht glücklich! Bohnen, Schokolade, Öl, Reis, Nudeln...
Bücherw.: Landkarten aus Papier, top aktuell, wer will sich neu orientieren? Büchw: Lexikons, Simultanübersetzungen sind von gestern, lernt Sprachen!

---

*Pestdoktor:* Bringt eure Elektroleichen! Elektroleichen!

---

*Ausrufer:* Neue Identitäten! Wenn nicht jetzt, wann wollt ihr euch dann neu erfinden? Ich helfe euch zur Legende zu werden!
Techie geht zum Adler und den Vögeln:

---

*TE:* Kennst du diesen alten Zauberer, Merlin oder so ähnlich, der sagt, es breche ein neues Zeitalter an und dass es gilt...

---

*Adler:* Aber sicher kenne ich ihn! Gerade hatten sie ihn wegen seinen Reden wieder in einen Turm eingesperrt und ich musste ihn ausfliegen. 

---

*TE:* und stimmt es, was er sagt?

---

*Adler:* Witterst du es etwa nicht, dass etwas Neues in der Luft liegt?

---

*Orakel:* Aber er sagt, wir müssen bewahren, was zu bewahren ist und nicht nur Neues schaffen!

---

*TE:* damit meint er eindeutig meine Tanks!
beim Orakel stehen Detektive mit Hund, Bloggerin, Techie, Professor an:

---

*DE 1:* Sag uns, wo finden wir Utopia und die untergegangene Welt?

---

*DE 2:* Und wie lautet das Geheimnis der Wundertüte?

---

*Orakel:* Alles in einem, eines in allem.

---

*Hund:* Das nennt sich wohl Orakelspruch!

---

*Te:* Schnell, kannst du mir meine Zukunft sagen? Das Geschäft ist gegroundet, alle Investitionen verloren...ich bin am Ende.

---

*Orakel:* Na, so schlimm wird es schon nicht sein, zeig mir mal deine Hände: Ah interessant, ich sehe Fische, Meeresnixen, und viel Wasser. Ich würde sagen, du schwimmst bald irgendwo!

---

*Te:* Ferien! das ist genau, was ich brauche, wunderbar, hier nimm mein letztes Geld!

---

*Bloggerin:* Und was kannst du mir voraussagen?

---

*Orakel:* Oh, eine Katastrophe, ganz schlimm, du fällst, aber du wirst gerettet und ich sehe dich an einem fernen unbekannten Ort.

---

*Bloggerin:* Naja, Katastrophen bin ich ja jetzt gewohnt, und fern und unbekannt tönt very exciting!

---

*Professor:* Schnell, sag mir, bin ich noch Professor?

---

*Orakel:* gib mir deine Hand: Oh du kannst dich freuen! Du wirst den Forschungsauftrag erhalten die neue kreative Armut zu untersuchen! Mach dir am besten schon jetzt Notizen!

---

*Professor:* Aber mein notebook ist vom Netz!

---

*Orakel:* Hattest du nicht das Wort kreativ in deinem Titel? Hier Papier und Bleistift, Handschrift tut es zur Not auch!

---

*Umfragemacher:* Sagen sie, was können sie sich eher vorstellen, den Weltuntergang oder eine Welt ohne Geld?

---

*Prof :* natürlich eine Welt ohne Geld, das wäre ja wirklich das kleinere Übel.

---

*U:* Und sie?

---

*Te:* dumme Frage, was bringt mir denn jetzt noch Geld? Hauptsache der Weltuntergang wird noch ein einziges Mal abgesagt und ich kann in die Ferien!
Bücherw.: Landkarten, Lexikons, Wörterbücher und Romane!
Bücherw.: Krimis, Romanzen, Tragödien, ein vollwertiger streaming-Ersatz!
Strassenhändlerin: Zeitlos, zeitlos! Bringt Licht ins Dunkel: Mitgefühl,.....

---

*Eule:* Schuhu! Schuhu!

---

*Kinder:* Die Nachtelfen kommen, die Nachtelfen kommen!
Viele Nachtelfen treffen ein, drängen die Leute mit Leuchtstäben zurück.

---

*Nachtelfe:* Ihr werdet fortan alle als unsere Diener in der Dunkelheit leben! Nachtelfe: Hört ihr? Alle!   sie lachen höhnisch

---

*Nachtelfe:* Und jetzt verzaubern wir euch!

TANZ der dunklen Nachtelfen
Jugendliche mit Trottis kommen.
Verk. 1: Notfallkits, Notfallkits! Ob Nachtelfenplage, Elektrizitätsausfall, Haarausfall, Überschwemmung, Vulkanausbruch, Erdbeben, Hungersnot, 
Verk. 2: bei uns findet ihr alles für Notfälle! Rüstet euch aus, dann kann euch nichts mehr passieren! Greift zu, es hat, solange es hat!

---

*J 1:* das brauche ich alles nicht, ich habe genug youtube-videos geschaut, ich weiss wie man Feuer macht und eine Hütte baut, welche Pflanzen uns Nahrung geben, welche Heilkräfte haben und ich kann auch alle Tiersprachen. 

---

*J 2:* In meinem Rucksack ist unsere Ausrüstung, habe ich alles vor einiger Zeit schon im Internet bestellt. Wir werden auf jeden Fall überleben und sicher Grossartiges entdecken. 

---

*J 3:* Unser Wunsch geht in Erfüllung, wir brechen auf!
Verkäufer: Aber habt ihr auch ein Ziel, ihr könnt doch nicht einfach....

---

*J 4:* Alle Wege sind offen und was wir finden, ist noch unbekannt.

---

*J 5:* Wir verlassen uns auf unsere Neugier!

---

*J 6:* Das ist das wahre Abenteuer!

---

*Merlin:* Wenn jemand das Land Utopia finden kann, dann diese Kinder!
Detektive waren in der Nähe:

---

*DE 1:* Wenn das nicht eine heisse Spur ist!

---

*J 1:* Schaut nur, die Eule dort mit dem Schal! Sie kommt mir so bekannt vor! J 2: Und sie winkt uns! 

---

*Eule:* Habt Geduld ihr Menschenkinder, bald erscheinen die Nachtblumen!

---

*DE 2:* Keine Zeit verlieren, Fahrzeuge besorgen und hinten nach!
Strassenhändlerin: Greift zu, für jede Krise geeignet, für jeden etwas dabei! Greift zu, alles gratis! Mitgefühl...
Lebensmittelhändler: Bohnen, Hafer, Sauerkraut!
Händler: Hamsterkaufen! Hamsterkaufen! Beruhigt sofort, gibt einem ein Ziel! Hamsterkaufen!

---

*Pestdoktor:* Elektroleichen! Elektroleichen!
Fledermäuse, die mit Viren spielen, zu sehen.

---

*Kater:* Was habt ihr denn da?
Fl.: Winzlinge, siehst du nicht?

---

*Kater:* Sind die wertvoll?
Fl.: Kommt ganz drauf an, und nun geht euren Geschäften nach!
Einkäufer mit seinem laptop:

---

*Eink:* Schnell, ich habe nur eine Viertelstunde, Hier: Bohrmaschine, gerade Aktion, schnell, so geschafft, die liegt im Einkaufswagen, jetzt zur Kasse.. 

---

*Aus Laptop:* Warum brauchen sie eine neue Bohrmaschine?

---

*Eink:* Was geht sie das an, na gut, also bei meiner ist der Stecker kaputt gegangen.

---

*Aus Laptop:* Wozu brauchen sie überhaupt eine Bohrmaschine?

---

*Eink:* Ja wofür wohl, zum Löcher bohren!

---

*LT:* Wie oft denken sie, werden sie die Bohrmaschine brauchen?

---

*Eink:* Das geht sie gar nichts an, hören sie auf meine Zeit zu stehlen, na gut, dann sage ich 3-4 mal!

---

*LT:* Die Bohrmaschine wurde aus ihrem Einkaufswagen entfernt. Hier sehen sie die Adresse von ihrem Nachbarn, er wird ihnen seine Bohrmaschine gratis ausleihen. Ihre kaputte Bohrmaschine bringen sie bitte zum Repaircafé in ihrem Quartier.

---

*Eink:* So hören sie, das können sie nicht machen, he hallo? Oh nein, meine ganze Viertelstunde ist drauf gegangen. He sie da drinnen, ist ihnen bewusst, dass so der ganze online-handel kaputtgeht?
Königin der Nacht, Engelstrompete, Mondblume und Nachtkerze kommen an, umflattert von 4 Nachtfaltern.

---

*Kinder:* Schaut nur dort: Die Königin der Nacht, die Engelstrompete, die Nachtkerze, und die Mondblume! Und jede hat einen Nachtfalter dabei!
Königin: wende dich besser dem zu, was man nicht bestellen kann. 

---

*Eink:* Gibt es so etwas überhaupt? Und falls ja, wie heisst es?
Königin: Fantasie, gute Einfälle, Zeit haben, Zuhören können. 

---

*Eink:* Und was bringt mir das ein?

---

*Mondblume:* Jemand, der nie gestresst und immer gute Ideen hat, wird sehr geschätzt!

---

*Nachtkerze:* Auch Eigenschaften wie hilfsbereit und mitfühlend sind ab sofort gefragte Sachen!

---

*Lotus:* Auch Vertrauen und Verzeihen sind sehr wertvoll!

---

*Mondblume:* Alles umsonst!

---

*Eink:* Ok, aber nochmal, was bringt das mir?

---

*Engelstrompete:* Wertschätzung statt Wertschöpfung!

---

*Lotus:* So gelangt man vom Wettstreit zur Zusammenarbeit! 

---

*Nachtkerze:* Und jetzt denke selbst darüber nach, wir müssen weiter.

---

*J:* Die nachtblühenden Pflanzen! Schnell, sie wissen den Weg nach Utopia!
Sie fahren ihnen nach. Wenig später die Detektive, gefolgt von Katzen.

---

*Kater:* Bringt die Räder zurück! Kater: haltet die Diebe!

---

*Fl:* Uns kann eine Krise gar nichts mehr anhaben!

---

*Fl:* Denn uns haben die Menschen damals bei der Pandemie die Schuld gegeben!

---

*Fl:* Das war gar nicht lustig und da hat mein Urgrossvater,

---

*Fl:* meiner auch! Fl: meiner auch! Fl: Und meine Urgrossmutter war auch dabei! Fl.: meine Urgrosstante auch! Fl.: mein Urgrossonkel auch!

---

*Merlin:* Also alle eure Urahnen haben beschlossen, als Virenjäger tätig zu werden. Das nannte man damals enkeltauglich handeln, erzählt weiter!

---

*Fl:* Und wir führen das Geschäft in 4. Generation fort!

---

*Fl:* Haben erweitert, neu kümmern wir uns auch um Bakterien!
Händler: Aber das ist doch total gefährlich, diese Biester so offen herumzutragen!

---

*Merlin:* nur mit der Ruhe, sie haben alle in Tiefschlaf versetzt, ich habe ihnen gezeigt wie.

---

*Fl:* Und nun sind sie in Quarantäne und wir versuchen sie auf andere Ideen zu bringen.
Händler: Und wenn das nicht klappt?

---

*Fuchs:* Keine Sorge, Viren sind Programme, die lassen sich einfach umprogrammieren!

---

*Fl:* Die schlauen Füchse sind bei uns als Programmierer tätig.

---

*Fuchs:* Bereits haben wir einige freigesetzt und der Erfolg ist vielversprechend! 

---

*Fuchs:* So ein winzig kleines Ding kann nämlich die Welt verändern!

---

*Merlin:* Und das Beste ist, dass diese Viren richtig Freude an ihren neuen Wirkungen haben, endlich werden sie nicht mehr bekämpft und angefeindet!
Händler: und was sind denn ihre neuen ungefährlichen Wirkungen?

---

*Fl:* die gelben hier verbreiten gute Laune/die grünen regen zum Denken an/
die blauen verhelfen zu guten Einfällen/der violette verbreitet Liebe/der rote Glück/und der orange Mitgefühl!

---

*Orakel:* Füchse hört zu! Die nächsten müsst ihr so programmieren, dass sie das Unmögliche möglich machen. Wenn ich in die Zukunft schaue, ja da sehe ich es, der Nobelpreis wird bald zum ersten Mal an die Tierwelt gehen.
Händler: Soso, hübsche Geschichte, nur zu schön um wahr zu sein. Hamsterkaufen! Hamsterkaufen!

---

*Bloggerin:* Merlin, warte! Könntest nicht du die Weltregierung übernehmen? Du bist so gescheit und hast alle Fähigkeiten um in diesen schlimmen Zeiten die Welt zu retten. /to save the world!

---

*Merlin:* Die Hilfe in grosser Not ist doch bereits meine jahrtausendealte und endlos weiter bestehende Aufgabe. Die Weltregierung aber müsst ihr selbst regeln, da verstehe ich zu wenig davon.
Elva mit einem Kübel Flossen und fliegendem Teppich

---

*Elva:* Nutzt die Gunst der Stunde! Denn alles was planmässig verläuft, gibt keine erzählenswerte Geschichte, nur das Zufällige und Unerwartete macht es interessant.

---

*Merlin:* Glaubt es, Menschen, nur Geschichten können das Chaos, in das sich die Welt gerade verwandelt, aufhalten!
Auftritt der 2 Eventmanager mit Schildern Ideapolis/Parolatopia und Utopia/Schatzinsel, mit ihnen BB8 und R2D2 mit Schild «Hotel Intergalaxial», 

---

*E1:* Wir vom Chaos-Reality-Event-Management haben alles im Griff. Wir bringen Entspannung und Lebensfreude, Vergesst alle Sorgen und vertraut uns einfach!

---

*E2:* Wie wäre es zum Beispiel mit einer Reise? Das ist immer passend. Oder wandert ihr lieber aus? Nach Ideapolis, auf die Schatzinsel?

---

*E1:* Oder bucht eine Suite im Hotel Intergalaxial samt Welnesspaket!

---

*E2:* entdeckt das sagenumwobene Atlantis oder bucht eine Fahrt ins Blaue! 

---

*E1:* Und bis wir alles organisiert haben, darf diese Märchenerzählerin eine ihrer Geschichten erzählen, was sagte sie schon wieder?

---

*GE:* Korallenriff, aber das ist nur ein Ort von vielen, ich kann auch

---

*E2:* Das Korallenriff ist ausgezeichnet. Das gehört zu den Orten, die man noch sehen muss, bevor es definitiv zu spät dafür ist. Wer wagt es?

---

*Einige stehen gleich an
E1:* Super, dann sucht noch weitere Reiselustige und trefft euch bei der Märchenerzählerin!
Sie ziehen die Flossen an.
Begegnung der Notvorrateinkäufer mit vielen Taschen und WC-Rollenwagen.
Einkäufer 2: Mein Lieblingsmüesli war schon ausverkauft, es hatte nur noch leere Haferflocken und erst noch in bio, naja man muss flexibel bleiben, habe gleich alle 15 Pack genommen.
Einkäufer 1: Ich habe gerade noch die letzten 20 Pack Penne ergattert.
Einkäufer 2: Und ich die Tomatensauce und den Käse dazu!
Einkäufer 3: Seht mal hier, damit mache ich das Geschäft des Lebens!

---

*Passant:* Neuerdings geht es um Wertschätzung und nicht mehr um Wertschöpfung, wisst ihr es noch nicht?
Einkäufer 4: Oh je, jetzt drehen die ersten schon durch, ist ja gut Kater, da, eine Tafel Schockolade, ist gut für die Nerven!
Secondhandhändlerin: Lasst euch voll Freude auf die neue, kreative Armut ein! Ihr wollt doch fortan nicht nur im Pyjama leben, nicht wahr? Dann lasst euch von uns inspirieren, Musik!

---

*Kater:* Die meisten Kleider, die die Menschen kaufen, miau,

---

*Kater:* tragen sie sowieso nie, miau!

---

*Hund:* Wo ihr recht habt, habt ihr recht, wuff, äh wau! Schaut nur, dort!
Die Einkäufer raffen währenddessen alle Kleider zusammen und gehen.

Modeschau aus secondhand-Kleidern

Elva, mit Schwimmzubehör, bei den Wartenden in Badehosen.

---

*GE:* Ihr wollt das letzte Korallenriff besuchen, stimmts?

---

*Schw:* Ja aber....

---

*GE:* Keine Sorge, ihr werdet es nicht bereuen!

---

*Schw:* Aber wie soll das gehen? Schon KI hat solche Reisen verboten!

---

*Schw:* Und streaming geht auch nicht mehr!

---

*GE:* Keine Angst, unsere Reise wird zu 100 Prozent klimaneutral sein.

---

*Schw:* Das ist doch gar nicht möglich!

---

*GE:* Wollt ihr jetzt das letzte Korallenriff sehen oder nicht? Dann werft euch in die Fluten und schwimmt! 
Musik, ein Korallenriff mit unzähligen Riffbewohnern erscheint.

---

*GE:* Ihr seid unterwegs zu einem Korallenriff, und bald seid ihr Teil dieses unendlich wertvollen Urwalds der Meere. 

---

*Sch:* Dass ich das erleben darf!

---

*Sch:* Das ist wirklich der Regenwald des Meeres!

---

*Sch:* Schau nur, die Seepferdchen und Tintenfische und...

---

*Sch:* Und dort hinten ist das Neptun?

---

*Ratte:* Nein, das ist doch Aquaman!

---

*GE:* Ihr habt Glück, gleich findet das grosse Meeresfest statt!
Die Schwimmer schwimmen hinter die Korallen...
Musik und die Meeresnixen, Seepferdchen und kleinen Nixen tanzen
Blaue Tücher vor Bühne? , dann Meeresrauschen+alles verschwindet

---

*
E1:* Seht ihr? Dank uns kehrt langsam wieder normale Reisetätigkeit ein.

---

*GE:* Das war aber meine Geschichte!

---

*E2:* Stimmt, du warst der erste Programmpunkt in unserer Show, gratuliere! E1: Schönen Abend noch!

---

*E2:* The show must go on, was sind eure geheimsten Wünsche?

---

*E1:* Wir erfüllen sie euch alle!
4 Damen in Reisekleidung, mit Koffern und Taschen am warten:
: Können sie mir eine Suite im Intergalaxial buchen? 
: Mir auch, meine Nerven, ich brauche dringend eine Auszeit.
: Für mich das Wellnesspaket dölüx!
: Ist die Jupitersuite noch frei?     

---

*Zu BB8 und R2D2:* 

---

*E1:* Führt sie zum stargate und gebt ihnen Ingwershots, 

---

*E 2:* damit sie im Wurmloch nicht raumkrank werden.

---

*E2:* Und schaut, dass sie auf der Raumstation nicht gleich von Piraten überfallen werden, es soll gerade einiges los sein dort draussen.
Die 2 kleinen Roboter wuseln mit Leuten davon.
Währenddessen kamen 7 weitere Reisefreudige an. 
2 Jugendliche, exkursionsmässig gekleidet, fahren durch:

---

*J1:* Komm mit uns Elva, damit du später allen von diesem sagenumwobenen Land Utopia berichten kannst!

---

*J3:* Schnell, steig auf deinen fliegenden Teppich!

---

*E1:* So die Dame hätten wir los. Wer hat noch nichts gefunden?
: ich! ich!......

---

*E2:* Wie wäre es mit dem Land Parolatopia?

---

*E1:* Parolatopia, ihr Erdlinge, das ist nämlich die Welt der Welten. Da gibt es nichts, was man nicht antreffen könnte, grüne Feen, Kobolde, 

---

*E2:* fliegende Drachen, Prinzen und Prinzessinnen, Hexen, Gespenster, Zwerge, wilde Kerle, Königinnen, Diener, Feen, Elfen, geflügelte Einhörner

---

*R 1:* Dort wimmelt es doch von Flüchtlingen!

---

*R 2:* Der Riese Buugel hat ihre Bücher digitalisiert und sie konnten sich nur knapp retten!

---

*E2:* Stimmt, aber es sind alles Mutige und Unerschrockene!

---

*R 3:* Trotzdem, ihr stellt Flüchtlinge zur Schau, statt ihnen zu helfen.

---

*E1:* dafür sind doch nicht wir zuständig, wir sorgen uns schon um euer Wohl in diesen schweren Zeiten, denkt doch mal nach, wie es euch sonst gehen würde!

---

*R 4:* Ich gehe zu den Flüchtlingen, vielleicht kann ich ihnen helfen, eine neue Heimat zu finden! Ich will endlich was Nützliches tun.

---

*R 1:* Ich auch, es gibt ja wirklich noch welche, denen es viel schlechter geht als uns. 

---

*R :* Für die kommt das, was wir gerade hier haben, ziemlich nahe an ihre Vorstellung vom Paradies!

---

*E1:* So fertig mit sentimentalem Geschwätz, wartet dort hinten auf die weisse Maus, sie öffnet euch bald das Gittertor! Viel Vergnügen!

---

*E2:* Huch, da sind wir nochmals gut davon gekommen.

---

*E1:* Schnell kümmern wir uns um den nächsten event, bevor die Lage richtig ungemütlich wird.
Musik.   Einige Schwarzgekleidete machen “Bänderstrudel”.
Parolatopia entsteht. 
Viele Märchenfiguren gehen alle ihrer Pflicht nach: Goldmarie im Garten, Pechmarie liegt faul herum, Frau Holle Kissen ausschütteln, Aschenputtel wäscht Kleider, gestiefelter Kater mit gefangenen Hühnern, Hexe Lebkuchen ans Haus hängen und dazu singen “Knusperknusperhäuschen....!”, Rotkäppchen mit Wölfen, Rumpelstilzchen mit Spinnrad und Stroh, Hänsel und Gretel suchen Heimweg, Schneewittchen im Glassarg, Froschkönig streitet mit Prinzessin, Schöne+Biest sitzen auf Bank, Schneeweisschen und Rosenrot spielen, das Schneiderlein verfolgt eine Fliege mit der Klatsche, die Biene Maja verteilt Briefe, Dornröschen schläft, Rapunzel lässt ihren Zopf runter, ein kleines Geisslein im Uhrenkästlein, Momo und Kassiopeia, Maurizio und Jakob.
Die Reisenden erscheinen von weisser Maus geführt.

---

*Maus:* Willkommen in Parolatopia!
Die Bremerstadtmusikanten(Hahn, Katze, Hund, Esel) machen Musik, Hofnarr als Dirigent. Harry Potter macht Zauberspruch und wünscht viel Magie

---

*Frau Holle:* Seid gegrüsst liebe Besucher! Meine beiden Maries sollen euch bewirten!

---

*Pechmarie:* Pah, sie sollen die Äpfel selbst vom Boden auflesen und das verbrannte Brot aus dem Ofen nehmen. Ich bin nicht zur Magd geboren, merk dir das endlich!

---

*Frau Holle:* Es tut mir leid, ihr seid im falschen Moment gekommen, Goldmarie arbeitet gerade im Gemüsegarten.
Bremerstadtmusikanten machen zum 2. Mal Musik, gehen dann.
Ein Junge bringt währenddessen Tischlein+Topf.

---

*Junge :* Tischlein deck dich! Wer ist denn heute mit ausgeben dran?
Die Schöne und das Biest: Wir! Wir sind ja schon unterwegs!

---

*Pechmarie:* Wir haben Hunger, müsst ihr denn immer herumturteln?
Alle, strecken Teller hin und werden verpflegt.

---

*R1:* Was für Zeiten! Märchen- und Traumgestalten erscheinen in Wirklichkeit!

---

*R2:* Die haben ja kaum Platz!

---

*R3:* Und die Armen können ihre Geschichte nicht weiterleben!

---

*Pechmarie:* das will ich auch nicht, ihr Touristen habt ja keine Ahnung! 

---

*R:* Dornröschen wird wohl nie mehr erwachen!
Dornröschen: Ich bin doch schon lange wach, ist einer von euch ein Prinz? Einen unechten würde ich auch nehmen!
Momo und Kassiopeia, Maurizio und Jakob kommen mit Gepäck:

---

*Jakob:* Ich und Maurizio haben doch kürzlich die Welt gerettet, aber wie sieht es denn hier aus? 

---

*Momo:* das glaubten wir auch! Sollen wir es zusammen nochmals versuchen?

---

*R4:* Dort muss Aschenputtel die Kleider im Fluss waschen und schau nur, wie armselig sie gekleidet sind.

---

*R2:* Ich verteile ihnen die warmen Decken.

---

*Pechmarie:* Kann ich zwei haben?

---

*R2:* Ah, wie lieb, du denkst an deine Schwester!

---

*Pechmarie:* Sicher nicht, die muss arbeiten, die braucht keine Decken!
Goldmarie bringt einen Korb voll mit frischen Karotten.

---

*Gestiefelter Kater:* Der Riese hat mir damals angeboten, armen Männern zu reichen Ehefrauen zu verhelfen mit meinem Kleidertrick und dem Hühnergeschenk, damals wollte ich nichts davon wissen, aber jetzt? Ja warum eigentlich nicht?

---

*R1:* Da musst du aber deinen Trick modernisieren Kater, sonst sperren sie dich gleich weg!

---

*Schneewittchen:* Mir geht es ganz ähnlich, Der Riese Buugel hat mir vorgeschlagen ein Putzinstitut zu gründen, ich werde es wagen! Alles ist besser als hier eingesperrt zu sein und auf einen Prinzen zu warten, der nie kommt, es ist so traurig.

---

*R 3:* Komm zu mir, ich gebe dir Arbeit, ich will endlich ein gutes Werk tun!

---

*Schneiderlein:* Nummer 4, jetzt noch 3!

---

*R 3:* Du musst 7 auf einen Schlag erwischen!

---

*Schneiderlein:* vergiss es, Butterbrote gibt es hier schon lange nicht mehr, also stör mich nicht, ich habe noch viel Näharbeit vor mir.

---

*Rumpelstilzchen:* Ach wie gut, dass niemand weiss, wie ich heiss.

---

*R 4:* Du bist doch Rumpelstilzchen, das weiss ich genau!

---

*Rumpelstilzchen:* Sei sofort still, die gierige Königin darf es nicht wissen!

---

*Prinzessin:* Kommt, wir tanzen für unsere Besucher!        
Jerusalema-Tanz

---

*Alice:* weiss jemand von euch den Weg ins Wunderland?

---

*R:* Ich glaube, du musst in eine Baumhöhle fallen!

---

*Hase1:* Komm Alice, wir begleiten dich! 

---

*Hase2:* Und ärgern die böse Königin!
Hänsel und Gretel: Und kann uns jemand den Weg nachhause zeigen?

---

*R 2:* Den sollt ihr doch gar nicht finden, habe ich gemeint, eure Eltern sind doch arm, haben kein Geld...
Hänsel: Eben darum sind wir zur Hexe in den Wald gegangen, sie gibt uns immer die alten Lebkuchen.

---

*Gretel:* Aber es ist so ein Gedränge hier, da verliert man die Orientierung!

---

*Beide:* Mama! Papa! Wo seid ihr?

---

*Hase:* Komm Alice, wir suchen das Wunderland!

---

*Die Detektive erscheinen:* 

---

*DE 1:* wir haben uns nur verirrt, weil du dieser Wundertütenmaus nachwolltest. Und dann haben wir die Kinder aus den Augen verloren.

---

*DE 2:* Immerhin sind wir dank der Maus nun hier! Da findet wohl gerade ein Maskenball statt? 

---

*Rapunzel:* Alarm es kommt jemand! Alarm! Eindringlinge!  (Sirene)
Die Legomännchen kommen über Steg und bauen ihre Strasse weiter. Die Reisenden gehen im Garten zuschauen, verschwinden dann.
Rotkäppchen: Hat euch der Riese Buugel geschickt?

---

*L:* Ach wo denkst du hin, uns schickt niemand, wir haben uns entschlossen 

---

*L:* eine Strasse in die Zukunft zu bauen! 

---

*L:* Der können alle folgen, die wollen.

---

*L:* Jeder kann seine Geschichte neu leben!

---

*L:* Einfach improvisieren, kommt gut!

---

*Maus:* Da nehmt sie mit und pass gut auf sie auf!
Rotkäppchen: weiss der Riese Buugel wirklich nichts von dieser Strasse?

---

*L:* Ach wie denn. Der kennt uns ja nicht einmal!

---

*L:* Und jetzt stört uns nicht, wir sind gleich wieder weg.

---

*L:* Seht nur, da wollen schon die Ersten über die neue Strasse, es pressiert!
Froschkönig: ich habe es so satt an die Wand geworfen zu werden, ich wandere aus und bleibe ein Frosch.

---

*Prinzessin:* Warte auf mich, ich verspreche dir...
Froschkönig: Vergiss es....
DE 2:“Strasse in die Zukunft” das tönt nicht schlecht, dem folgen wir!

---

*DE 1:* Siehst du das? Die Tüte wurde übergeben, schnell!
Froschkönig: Nicht drängeln junger Mann, sondern hinten anstehen und Abstand halten!
Nun gehen sie über die Strasse davon, zuhinterst die ungeduldigen Detektive.

---

*Weisse Maus:* Die werden ihre neuen Geschichten finden und Elva wird uns davon berichten! Gute Reise!
Sie winkt und schaut ihnen zu, wie sie zu Musik davongehen. 
Währenddessen, die Eventmanager auf der Seite:

---

*E1:* mir ist schon nicht so wohl mit dieser letzten Reise, die wir im Angebot haben. Schliesslich waren wir noch nie in diesem Utopia und wissen nicht, was die Leute erwartet.

---

*E2:* Aber wer soll denn dieses ultimativ neuste Reiseziel anbieten, wenn nicht wir? Schliesslich spricht man seit vielen hundert Jahren von diesem sagenhaften Land! Komm jetzt, sie werden ungeduldig.
Die Bloggerin mit Katze, die Journalistin, die Architektin, die Ratte, der Professor, der Baumforscher, der Techie

---

*TE:* eine Unverschämtheit uns solange warten zu lassen.

---

*Architektin:* das hätte KI niemals zugelassen! Ich brauche dringend ein neues Weltbild, da läuft gerade ein grosser Architektur-Wettbewerb dazu, den ich gewinnen muss!

---

*Bloggerin:* And I need some inspiration for the “neue Miteinander”!

---

*Forscher:* Es gibt noch unendlich viele Bäume, die ich kennenlernen möchte.

---

*Ratte:* ich komme aus Neugier mit, was soll ich noch da, so alleine, schliesslich bin ich das Tier des Jahres!
Ein fliegender Ballon zu sehen.

---

*Journalistin:* Wo soll es überhaupt hingehen? Weiss das jemand?

---

*E2:* Da sind wir schon, haben alles gut vorbereitet!

---

*E1:* Eure Reise führt ins Land Utopia! 

---

*E2:* Na? Überraschung gelungen?

---

*BL:* Kommen sie uns nicht mit solchen Luftschlössern...

---

*Prof:* Doch doch, das kreative Schrumpfen nennt man gerne utopisch, ich bin dabei!

---

*Te:* Und ich muss Utopia als neueste Wunschwelt designen, dass wird mein Geschäft wieder zum Laufen bringen!

---

*BF:* Ich werde dort sicher ganz neue Bäume entdecken, die selbst der Mammutbaum noch nicht kennt!

---

*Katze:* Miau, wo liegt es denn, dieses Utopia?

---

*Ratte:* es ist überall und nirgendwo.

---

*Katze:* du hältst dich wohl für besonders schlau, was Ratte?

---

*Journalistin:* Ich liebe es, ins Ungewisse und Unbekannte zu springen. Wie die ersten Raumfahrer, damals in den Galaxien!

---

*E2:* Um es zu finden, müsst ihr fliegen!

---

*Alle:* geht nicht, machen wir nicht mehr.

---

*E2:* Wie ihr wollt, ist aber die letzte Chance diesem Chaos hier zu entfliehen.

---

*E1:* Ausserdem hat es nur 4 Plätze und wenn ihr alle mitkommen wollt, wird sowieso das Los entscheiden.

---

*E2:* Wer wagt, gewinnt! 
Lose werden gezogen.

---

*E1:* Gewinner nach rechts, Verlierer nach links!
Alle rennen nach rechts.
Der Mond ist aufgegangen, Sterne und Planeten sind zu sehen. Adler

---

*E1:* das wird eine Katastrophe geben, ich sag es dir! Zudem bricht schon die Nacht herein.

---

*E2:* meinst du, sie versuchen wirklich alle in den Korb reinzukommen?

---

*E1:* Da kannst du Gift drauf nehmen! Sie werden abstürzen, bevor sie auch nur über Utopia sind.

---

*E2:* Hoffentlich nicht dort, wo die Krokodile im Fluss baden. Die haben doch sicher schon vergessen, dass KI die Menschen und Tiere gleichgestellt hat.

---

*E1:* Da ist doch so ein Hypersprung auf die nächste Raumstation der reinste Sonntagsspaziergang.

---

*E2:* von wegen, wir haben den videocall mit dem Hoteldirektor des intergalaxial vergessen, unsere Kunden erwarten.....

---

*Stimme:* Hier Reception Hotel Intergalaxial, wir warten schon eine gefühlte Ewigkeit auf euren call!

---

*E2:* Tut uns leid, wir haben keine Bildverbindung, könnt ihr uns sehen?

---

*Stimme:* Hallo, einwandfrei, ihr seht richtig abgekämpft aus!

---

*E1:* Hole einen Techniker, schnell, oder hast du schon mal von einem Videocall ohne Bild gehört?

---

*E2:* Schon X-mal, liegt in der Natur der Sache, reg dich nicht auf.

---

*Stimme:* Ich fürchte, es bleibt keine Zeit für Reparaturen, es kommt eine dringliche Durchsage herein, ich schalte sie zu:

---

*Durchsage:* Achtung, Achtung! An alle, die sich im Hotel Intergalaxial aufhalten: Da in den nächsten Tagen mit Raumstürmen und damit verbundenen Kometenschwärmen zu rechnen ist, wäre jetzt die letzte Möglichkeit auf die Erde zurückzukehren.

---

*E1:* Nein, nicht das auch noch! Schnell, stellen sie Verbindung her zu den Gästen, die wir geschickt haben.

---

*G 1:* Also ich bleibe. Was soll ich zuhause? 

---

*G 2:* Ich auch, denn auf der Erde muss erst wieder der Alltag einkehren.

---

*G 3:* Ich habe schon einen Flug zum nächsten bewohnten Planeten gebucht!

---

*G 4:* Irgendwo musst du dein Geld ja ausgeben.

---

*G 3:* Nun seid bloss nicht eingeschnappt, ich habe für alle von uns gebucht!

---

*Alle jubeln
E 1:* Das wärs gewesen, meine Viertelstunde Internet ist um. Dann können wir uns ja endlich um den Ballon kümmern. Du hast doch die genaue Position?

---

*E 1:* Hatte sie, um genau zu sein, dann war nämlich meine Viertelstunde Internet auch um.

---

*E 2:* halb so schlimm, sind alles erwachsene Leute, die werden sich schon über die Runden bringen. 

---

*E 1:* Stimmt, dann erwischen wir nämlich gerade noch das letzte Schiff auf die Schatzinsel, dort soll es neu einen Unterwasser-Escaperoom in einem gesunkenen Piratenschiff geben.

---

*Musik:* Ein Regenwald mit Bäumen, Pilzen, Gebüschen, Pflanzen entsteht. Kobolde und viele Tiere schauen hinter den Bäumen hervor. 
Musik und 2 Regenwaldbewohner tanzen.

---

*
Mond:* Guten Abend, gute Nacht ihr Erdlinge. Oh, da ist ja noch allerlei los, was liegt denn Geheimnisvolles in der Luft? 

---

*Mammutbaum:* Tief einatmen, Mond, dann riechst auch du das Neue!

---

*Pilz:* geschafft! Wir haben es geschafft! 

---

*Mond:* Und wie lautet die gute Nachricht?

---

*Pilz:* nach jahrelangen Bemühungen gelang es uns soeben, unser Netzwerk mit dem von unserem neuen Nachbarland Utopia zu verbinden!

---

*Pflanze:* Bist du ganz sicher, dass es dieses Land überhaupt gibt?

---

*Pflanze:* Vielleicht erlaubt sich da jemand einen Spass mit euch.

---

*Pilz:* zumindest haben wir den sicheren Beweis, dass es da draussen ein neues Netzwerk gibt.

---

*Pilz:* Wir empfangen eine Nachricht nach der anderen.

---

*Pilz:* Leider alles verschlüsselt. Wo stecken bloss die schlauen Füchse?

---

*Pilz:* habe ihnen schon getextet, sie sind unterwegs.

---

*Adler:* Wacht auf Bäume! Es liegt etwas in der Luft!

---

*Baum:* Du meinst wir erleben gleich etwas? Ich liebe Überraschungen!

---

*Affen:* Es kommt jemand!
Füchse erscheinen.

---

*Fuchs:* Da sind wir, die schlauen und schnellen Füchse! 

---

*Fuchs:* Was können wir helfen?

---

*Pilz:* Könnt ihr das entschlüsseln? Es kommt von utopia-punkt-universa.

---

*Fuchs:* Moment, das haben wir gleich: sie schreiben, ein unbekanntes Flugobjekt ist an der Grenze zwischen hier und Utopia am abstürzen.

---

*Pilz:* Und was noch?        (sie versuchen weiter zu entschlüsseln)

---

*Affen:* Es kommt schon wieder jemand!
Die strassenbauenden Legomännchen mit der grössten Wundertüte, legen sie hin und Kobolde holen sie. Den Bauarbeitern folgen: Frosch, Prinzessin, weisse Maus und die 2 Detektive. Die Bäume sprechen ganz langsam: 

---

*Baum:* he, ihr dort, was habt ihr im Sinn?

---

*Baum:* Wollt ihr uns fällen und durch Ölpalmen ersetzen? 

---

*Baum:* Macht ihr darum eine Strasse?

---

*Baum:* Oder sucht ihr nach Erdöl?

---

*Baum:* Nach anderen Bodenschätzen?

---

*Baum:* Egal, nehmen wir sie fest.
Jeder Baum hält einen fest. Papagei plappert ihnen im folgenden nach:
Legomännchen: Hilfe, zu Hilfe! Wir wollen euch nichts Böses,

---

*L:* wir bauen nur eine Strasse in die Zukunft!

---

*L:* Ohne Plan, wir improvisieren!

---

*L:* Bitte glaubt uns und lasst uns weiterarbeiten! 

---

*Mammutbaum:* sie schmecken ehrlich, lassen wir sie frei.
Rotkäppchen: Es stimmt, was sie sagen, lasst sie weiterbauen!
Während sie weiterziehen, ertönt ein grosser Absturzlärm.

---

*Pilz:* Das war weiter unten am Fluss, bei den Krokodilen!

---

*Pilz:* Da ist etwas Schlimmes passiert!
Da kommen Krokodil, Gürteltier, Waran aufgeregt angewuselt.

---

*Krokodil:* Es sind Menschen in einem Korb vom Himmel gefallen. Sie jammern und stöhnen, da vergeht einem ja direkt der Appetit!
Gürteltier: Einige sind an einem Korb gehangen, 

---

*Waran:* Und überall liegt zerissener Stoff!

---

*Mammutbaum:* Kobolde, wo seid ihr?
Die Kobolde schlüpfen zwischen den Bäumen hervor.

---

*Kobold:* Warum rufst du uns, du weisester aller weisen Bäume?

---

*MB:* Geht mit diesen dreien und bringt die Abgestürzten hierher.

---

*Kobold:* meinst du diese Menschen aus dem Korb?

---

*MB:* Wusste ich es doch, dass ihr gelauscht habt. Dafür macht ihr jetzt doppelt so schnell!
Die Kobolde bringen den Ballon mit den Menschen, die einen klammern sich unten immer noch dran. Ein grosses Gezeter. 
: Ihr seid schuld, weil ihr euch unten angeklammert habt!
: nein ihr, weil ihr uns nicht euer Los gegeben habt!: Nein ihr!: Ihr!
Usw.
Die Bäume, Pilze und Tiere rufen alle: Ruhe! 
Augenblicklich herrscht Totenstille. Die Abgestürzten schauen sich vorsichtig um, während die Jugendlichen auf ihren Trottis vorbeikommen. Sie haben Elva dabei und erhalten von den Kobolden die 3. Wundertüte. 

---

*Architektin:* He, ihr dort, könnt ihr uns sagen, wo wir sind?
Die Jugendlichen beraten sich.

---

*J:* In einem abgestürzten Heissluftballon!

---

*Te 1:* Das wissen wir doch selbst, wir meinen, wo sind wir hier?
Die Jugendlichen schauen sich um.

---

*J:* Bäume, Tiere, Pilze, Rotkäppchen, Wölfe, Kobolde, ich würde sagen, irgendwo zwischen Traum und Wirklichkeit.

---

*Professor:* Da wollten wir aber nicht hin! 

---

*Journalistin:* Moment, wohin seid denn ihr unterwegs?

---

*J:* Nach Utopia, wohin den sonst!
Sie fahren weiter.

---

*Pilz:* Glaubt ihr uns jetzt, dass es dieses sagenumwobene Land Utopia wirklich gibt?

---

*Architektin:* So wartet doch, lasst uns vor!

---

*Bloggerin:* I wanna be the first in Utopia!!

---

*J:* Holt uns ein, wenn ihr könnt!

---

*De:* Schnell hintennach, unsere Fälle sind so gut wie gelöst!
Sie und die Reisenden gehen ihnen schnell nach. Katze sitzt zum Mond.

---

*Affen:* Elva! Elva! Komm zu uns! Wir möchten die neuste Geschichte hören!

---

*Elva:* Die erzähle ich euch gerne, hört gut zu! Es war einmal....
Ein Schiff kommt an.

---

*E1:* Wo sind wir denn jetzt gelandet?

---

*E2:* Im Kleingedruckten stand doch, wer das escaperoom-Rätsel löst, wird eine grossartige Überraschung erleben.

---

*Fuchs:* Wen haben wir denn da? Die Eventmanager! Da habt ihr wohl Glück gehabt, dass den Ballonfahrern nichts passiert ist!

---

*E1:* Recht hast du, Fuchs, und da bleibt uns wohl nichts anderes übrig, als dieses sagenhafte Land Utopia endlich selbst zu erkunden.

---

*Fuchs:* Sehr vernünftig. Fahrt den Fluss runter, nicht weit von den Krokodilen befindet sich der Grenzübertritt.

---

*Kobold:* Und wir versuchen dieses Ding zu reparieren und 

---

*Kobold:* dann fliegen auch wir nach Utopia!

---

*Kobold:* Und dann bieten wir Rundflüge an!

---

*Mond:* Was für eine wunderbare Welt, findet ihr nicht auch? 

---

*Katze:* Miau, ich hätte zu gerne erfahren, was es in dieser Wundertüte hat.

---

*Mond:* Ein Wunder natürlich, was denn sonst, liebe Katze? Und jetzt 
wünsche ich euch allen eine gute Nacht!

ENDE





